kepanitiaan/urls.py
from django.urls import path
from .views import list_of_kepanitiaan, delete_kepanitiaan, form_add_kepanitiaan, form_update_kepanitiaan
urlpatterns = [
    path('', list_of_kepanitiaan, name='index'),
    path('add_kepanitiaan/', form_add_kepanitiaan, name='add_kepanitiaan'),
    path('update_kepanitiaan/<str:id_kepanitiaan>/', form_update_kepanitiaan, name='update_kepanitiaan'),
    path('delete_kepanitiaan/<str:id_kepanitiaan>/', delete_kepanitiaan, name='delete_kepanitiaan'),
]

main/urls.py
from django.urls import path
from .views import main_index, logout

urlpatterns = [
    path('', main_index, name='index'),
    path('logout/', logout, name='logout'),
]

simui/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('login.urls', 'login'), namespace="login")),
    path('main/', include(('main.urls', 'main'), namespace="main")),
    path('organisasi/', include(('organisasi.urls', 'organisasi'), namespace="organisasi")),
    path('kepanitiaan/', include(('kepanitiaan.urls', 'kepanitiaan'), namespace="kepanitiaan")),
    path('event/', include(('event.urls', 'event'), namespace="event")),
]

kepanitiaan/models.py
from django.db import models

# Create your models here.

kepanitiaan/forms.py
from django import forms
from simui_db.models import *

TINGKATAN_CHOICES = []
KATEGORI_CHOICES = []
ORGANISASI_CHOICES = []

tingkatan_data = list(PembuatEvent.objects.raw("SELECT DISTINCT id, tingkatan FROM pembuat_event"))
kategori_data = list(PembuatEvent.objects.raw("SELECT DISTINCT id, kategori FROM pembuat_event"))
organisasi_data = list(PembuatEvent.objects.raw("SELECT DISTINCT id, nama FROM pembuat_event pe, organisasi o WHERE pe.id = o.id_organisasi"))

for i in range(len(tingkatan_data)):
    if (tingkatan_data[i].tingkatan, tingkatan_data[i].tingkatan) not in TINGKATAN_CHOICES:
        TINGKATAN_CHOICES.append((tingkatan_data[i].tingkatan, tingkatan_data[i].tingkatan))
for i in range(len(kategori_data)):
    if (kategori_data[i].kategori, kategori_data[i].kategori) not in KATEGORI_CHOICES:
        KATEGORI_CHOICES.append((kategori_data[i].kategori, kategori_data[i].kategori))

for i in range(len(organisasi_data)):
    if (organisasi_data[i].id, organisasi_data[i].nama) not in ORGANISASI_CHOICES:
        ORGANISASI_CHOICES.append((organisasi_data[i].id, organisasi_data[i].nama))

class OrganisasiChoice(forms.Form):
    organisasi = forms.ChoiceField(
        choices=ORGANISASI_CHOICES,
        required=True,
        widget=forms.Select(
            attrs={
                'class': 'btn btn-primary dropdown-toggle dropdown-toggle-split',
                'data-toggle': 'dropdown',
                'aria-expanded': 'false',
                'type': 'button',
            }
        )
    )

class TingkatanChoice(forms.Form):
    tingkatan = forms.ChoiceField(
        choices=TINGKATAN_CHOICES,
        required=True,
        widget=forms.Select(
            attrs={
                'class':'btn btn-primary dropdown-toggle dropdown-toggle-split',
                'data-toggle': 'dropdown',
                'aria-expanded': 'false',
                'type': 'button',
            }
        ),
    )

class KategoriChoice(forms.Form):
    kategori = forms.ChoiceField(
        choices=KATEGORI_CHOICES,
        required=True,
        widget=forms.Select(
            attrs={
                'class':'form-control',
            }
        ),
    )

kepanitiaan/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.db import connection
from simui_db.models import *
from .forms import TingkatanChoice, KategoriChoice, OrganisasiChoice

response = {
	'kepanitiaan_title': 'Organisasi - Sistem Informasi Mahasiswa UI (SIMUI)',
	'author': 'Basis Data Ganjil 2018/19',
	'tingkatan_dropdown' : TingkatanChoice(),
	'kategori_dropdown' : KategoriChoice(),
    'organisasi_dropdown': OrganisasiChoice(),
}

def list_of_kepanitiaan(request):
	list_kepanitiaan = list(PembuatEvent.objects.raw("SELECT * FROM pembuat_event pe, kepanitiaan k WHERE pe.id = k.id_kepanitiaan ORDER BY pe.id DESC"))

	response['list_kepanitiaan'] = list_kepanitiaan

	html = "list_kepanitiaan.html"
	return render(request, html, response)

def form_add_kepanitiaan(request):
	print("hehe")
	latest_id = list(PembuatEvent.objects.raw("SELECT * FROM pembuat_event ORDER BY id DESC"))[0].id
	id_id = int(latest_id[-2:]) + 1
	final_id = 'R00' + str(id_id)

	if request.method == 'POST':
		id = final_id
		id_organisasi = request.POST['id_organisasi']
		nama_kepanitiaan = request.POST['nama_kepanitiaan']
		tingkatan = request.POST['tingkatan']
		email = request.POST['email']
		website = request.POST['website']
		contact_person = request.POST['contact_person']
		kategori = request.POST['kategori']
		deskripsi = request.POST['deskripsi']

		with connection.cursor() as c:
			sql = "INSERT INTO pembuat_event (id, nama, email, alamat_website, tingkatan, kategori, deskripsi, contact_person, logo) VALUES ('%s','%s','%s','%s','%s','%s','%s','%s',NULL)" % (id, nama_kepanitiaan, email, website, tingkatan, kategori, deskripsi, contact_person)
			sql1 = "INSERT INTO kepanitiaan (id_kepanitiaan, id_organisasi) VALUES ('%s','%s')" % (id, id_organisasi)
			c.execute(sql)
			c.execute(sql1)

		return HttpResponseRedirect(reverse('kepanitiaan:index'))

	else:
		html = "add_kepanitiaan.html"
		return render(request, html, response)

def form_update_kepanitiaan(request, id_kepanitiaan):
	response['id_current'] = id_kepanitiaan
	if request.method == 'POST':
		id = id_kepanitiaan
		nama_kepanitiaan = request.POST['nama_kepanitiaan']
		tingkatan = request.POST['tingkatan']
		email = request.POST['email']
		website = request.POST['website']
		contact_person = request.POST['contact_person']
		kategori = request.POST['kategori']
		deskripsi = request.POST['deskripsi']

		with connection.cursor() as c:
			sql = "UPDATE pembuat_event SET nama = '%s', tingkatan = '%s', email = '%s', website = '%s', contact_person = '%s', kategori = '%s', deskripsi = '%s' WHERE id = '%s'" % (nama_kepanitiaan, email, website, tingkatan, kategori, deskripsi, contact_person, id)
			c.execute(sql)

		return HttpResponseRedirect(reverse('kepanitiaan:index'))
	else:
		html = "update_kepanitiaan.html"
		return render(request, html, response)

def delete_kepanitiaan(request, id_kepanitiaan):
	with connection.cursor() as c:
		c.execute("DELETE FROM kepanitiaan WHERE id_kepanitiaan= '%s'", [id_kepanitiaan])
		return HttpResponseRedirect(reverse('main:index'))

kepanitiaan/templates/add_kepanitiaan.html
{% extends "layout/base.html" %}

{% block content %}
  <div class="py-5 text-center text-white" style="background-image: linear-gradient(rgba(0, 0, 0, 0.75), rgba(0, 0, 0, 0.75)), url(https://static.pingendo.com/cover-bubble-dark.svg); background-position: center center, center center; background-size: cover, cover; background-repeat: repeat, repeat;">
    <div class="container">
      <div class="row" style="">
        <div class="mx-auto col-md-10 p-4">
          <h1 class="text-light"><b>Pendaftaran Kepanitiaan Baru</b></h1>
          <p class="mb-4 lead text-light">Bantu kami memperkaya database kami dengan mendaftar. Pendaftaran gratis, tidak dipungut biaya.<br></p>

            <form action="{% url 'kepanitiaan:add_kepanitiaan' %}" method="POST">
            {% csrf_token %}
            <div class="form-row">
              <div class="form-group col-md-4"> <input type="text" class="form-control" name="nama_kepanitiaan" id="nama_kepanitiaan" placeholder="Nama kepanitiaan" required="required"> </div>
              <div class="form-group col-md-4"> <input type="email" class="form-control" name="email" id="email" placeholder="Email"> </div>
              <div class="form-group col-md-4"> <input type="text" class="form-control" id="contact_person" name="contact_person" placeholder="Contact Person"> </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-4">
                  <input type="text" class="form-control" id="website" name="website" placeholder="Website" required="required"> </div>
                    <div class="form-group col-md-4">
                    <div class="btn-group">
                      <select name="tingkatan" id="tingkatan" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <option selected="selected" disabled>Tingkatan Kepanitiaan</option>
                          {% for x,y in tingkatan_dropdown.fields.tingkatan.choices %}
                              <option value="{{ x }}" class="dropdown-item">{{ x }}</option>
                          {% endfor %}
                      </select>
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                    </div>
                  </div>
              <div class="form-group col-md-4">
                  <div class="btn-group">
                      <select name="kategori" id="kategori" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <option selected="selected" disabled>Kategori Kepanitiaan</option>
                          {% for x,y in kategori_dropdown.fields.kategori.choices %}
                              <option value="{{ x }}" class="dropdown-item">{{ x }}</option>
                          {% endfor %}
                      </select>
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                  </div>
              </div>
            </div>
            <div class="form-group"> <textarea class="form-control" id="deskripsi" name="deskripsi" rows="3" placeholder="Deskripsi Singkat kepanitiaan"></textarea> </div>
            <div class="form-group col-md-4">
                  <div class="btn-group">
                      <select name="id_organisasi" id="id_organisasi" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <option selected="selected" disabled>Nama Organisasi</option>
                          {% for x,y in organisasi_dropdown.fields.organisasi.choices %}
                              <option value="{{ x }}" class="dropdown-item">{{ y }}</option>
                          {% endfor %}
                      </select>
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                  </div>
              </div>
            <button type="submit" class="btn btn-secondary">Daftarkan!</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

kepanitiaan/templates/list_kepanitiaan.html
{% extends "layout/base.html" %}

{% block content %}
<div class="py-5" style="background-image: url(https://static.pingendo.com/cover-bubble-dark.svg); background-position: right bottom;  background-size: cover; background-repeat: repeat; background-attachment: fixed;">
    <div class="container">
      <div class="row">
        <div class="mx-auto col-md-8 text-center">
          <h1 contenteditable="true"><b>Daftar Kepanitiaan</b></h1>
          <div class="row">
            <div class="col-md-12"><a class="btn btn-primary" href="{% url 'kepanitiaan:add_kepanitiaan' %}"><b><b>Tambahkan kepanitiaan baru...</b></b></a></div>
          </div>
        </div>
      </div>

      <div class="row">
        {% for kepanitiaan in list_kepanitiaan %}
            <div class="col-lg-3 col-6 p-3">
              <div class="card"> <img class="card-img-top" src="https://static.pingendo.com/img-placeholder-1.svg" alt="Card image cap">
                <div class="card-body">
                  <h5 class="card-title"> <b>{{ kepanitiaan.nama }}</b> </h5>
                  <p class="card-text">{{ kepanitiaan.kategori }} | {{ kepanitiaan.tingkatan }}</p>
                  <p class="card-text">Email: {{ kepanitiaan.email }}</p>
                  <a href="{{ kepanitiaan.website }}"><p class="card-text">Website</p></a>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12 my-2"><a class="btn btn-primary" href="{% url 'kepanitiaan:update_kepanitiaan' kepanitiaan.id %}"><b>&nbsp; Update kepanitiaan...&nbsp;</b></a></div>
              </div><a class="btn btn-danger" href="{% url 'kepanitiaan:delete_kepanitiaan' kepanitiaan.id %}"><b>&nbsp; Delete kepanitiaan...&nbsp; &nbsp;</b></a>
            </div>
        {% endfor %}
      </div>
    </div>
</div>

{% endblock %}

kepanitiaan/templates/update_kepanitiaan.html
{% extends "layout/base.html" %}

{% block content %}
  <div class="py-5 text-center text-white" style="background-image: linear-gradient(rgba(0, 0, 0, 0.75), rgba(0, 0, 0, 0.75)), url(https://static.pingendo.com/cover-bubble-dark.svg); background-position: center center, center center; background-size: cover, cover; background-repeat: repeat, repeat;">
    <div class="container">
      <div class="row" style="">
        <div class="mx-auto col-md-10 p-4">
          <h1 class="text-light"><b>Pembaruan Informasi Kepanitiaan</b></h1>
          <p class="mb-4 lead text-light">Bantu kami memperkaya database kami dengan memperbarui informasi terkait kepanitiaan.<br></p>

            <form action="{% url 'kepanitiaan:update_kepanitiaan' id_current %}" method="POST">
            {% csrf_token %}
            <div class="form-row">
              <div class="form-group col-md-4"> <input type="text" class="form-control" name="nama_kepanitiaan" id="nama_kepanitiaan" placeholder="Nama kepanitiaan" required="required"> </div>
              <div class="form-group col-md-4"> <input type="email" class="form-control" name="email" id="email" placeholder="Email"> </div>
              <div class="form-group col-md-4"> <input type="text" class="form-control" id="contact_person" name="contact_person" placeholder="Contact Person"> </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-4">
                  <input type="text" class="form-control" id="website" name="website" placeholder="Website" required="required"> </div>
                  <div class="form-group col-md-4">
                    <div class="btn-group">
                      <select name="tingkatan" id="tingkatan" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <option selected="selected" disabled>Tingkatan Kepanitiaan</option>
                          {% for x,y in tingkatan_dropdown.fields.tingkatan.choices %}
                              <option value="{{ x }}" class="dropdown-item">{{ x }}</option>
                          {% endfor %}
                      </select>
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                    </div>
                  </div>
              <div class="form-group col-md-4">
                  <div class="btn-group">
                      <select name="kategori" id="kategori" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <option selected="selected" disabled>Kategori Kepanitiaan</option>
                          {% for x,y in kategori_dropdown.fields.kategori.choices %}
                              <option value="{{ x }}" class="dropdown-item">{{ x }}</option>
                          {% endfor %}
                      </select>
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                  </div>
              </div>
            </div>
            <div class="form-group"> <textarea class="form-control" id="deskripsi" name="deskripsi" rows="3" placeholder="Deskripsi Singkat Kepanitiaan"></textarea> </div>
            <div class="form-group col-md-4">
                  <div class="btn-group">
                      <select name="id_organisasi" id="id_organisasi" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <option selected="selected" disabled>Nama Organisasi</option>
                          {% for x,y in organisasi_dropdown.fields.organisasi.choices %}
                              <option value="{{ x }}" class="dropdown-item">{{ y }}</option>
                          {% endfor %}
                      </select>
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                  </div>
              </div>
            <button type="submit" class="btn btn-secondary">Daftarkan!</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}