main/urls.py
from django.urls import path
from .views import main_index, logout

urlpatterns = [
    path('', main_index, name='index'),
    path('logout/', logout, name='logout'),
]

organisasi/urls.py
from django.urls import path
from .views import list_of_organisasi, delete_organisasi, form_add_organisasi, form_update_organisasi

urlpatterns = [
    path('', list_of_organisasi, name='index'),
    path('add_organisasi/', form_add_organisasi, name='add_organisasi'),
    path('update_organisasi/<str:id_organisasi>/', form_update_organisasi, name='update_organisasi'),
    path('delete_organisasi/<str:id_organisasi>/', delete_organisasi, name='delete_organisasi'),
]

simui/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('login.urls', 'login'), namespace="login")),
    path('main/', include(('main.urls', 'main'), namespace="main")),
    path('organisasi/', include(('organisasi.urls', 'organisasi'), namespace="organisasi")),
    path('kepanitiaan/', include(('kepanitiaan.urls', 'kepanitiaan'), namespace="kepanitiaan")),
    path('event/', include(('event.urls', 'event'), namespace="event")),
]

organisasi/models.py
from django.db import models

# Create your models here.

organisasi/forms.py
from django import forms
from simui_db.models import *

TINGKATAN_CHOICES = []
KATEGORI_CHOICES = []

tingkatan_data = list(PembuatEvent.objects.raw("SELECT DISTINCT id, tingkatan FROM pembuat_event"))
kategori_data = list(PembuatEvent.objects.raw("SELECT DISTINCT id, kategori FROM pembuat_event"))

for i in range(len(tingkatan_data)):
    if (tingkatan_data[i].tingkatan, tingkatan_data[i].tingkatan) not in TINGKATAN_CHOICES:
        TINGKATAN_CHOICES.append((tingkatan_data[i].tingkatan, tingkatan_data[i].tingkatan))
for i in range(len(kategori_data)):
    if (kategori_data[i].kategori, kategori_data[i].kategori) not in KATEGORI_CHOICES:
        KATEGORI_CHOICES.append((kategori_data[i].kategori, kategori_data[i].kategori))

class TingkatanChoice(forms.Form):
    tingkatan = forms.ChoiceField(
        choices=TINGKATAN_CHOICES,
        required=True,
        widget=forms.Select(
            attrs={
                'class':'btn btn-primary dropdown-toggle dropdown-toggle-split',
                'data-toggle': 'dropdown',
                'aria-expanded': 'false',
                'type': 'button',
            }
        ),
    )

class KategoriChoice(forms.Form):
    kategori = forms.ChoiceField(
        choices=KATEGORI_CHOICES,
        required=True,
        widget=forms.Select(
            attrs={
                'class':'form-control',
            }
        ),
    )

organisasi/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.db import connection
from simui_db.models import *
from .forms import TingkatanChoice, KategoriChoice

response = {
	'organisasi_title': 'Organisasi - Sistem Informasi Mahasiswa UI (SIMUI)',
	'author': 'Basis Data Ganjil 2018/19',
    'tingkatan_dropdown' : TingkatanChoice(),
    'kategori_dropdown' : KategoriChoice(),
}

def list_of_organisasi(request):
	list_organisasi = list(Organisasi.objects.raw("SELECT * FROM pembuat_event pe, organisasi o WHERE pe.id = o.id_organisasi ORDER BY pe.id DESC"))

	response['list_organisasi'] = list_organisasi

	html = "list_organisasi.html"
	return render(request, html, response)

def form_add_organisasi(request):
	print("hehe")
	latest_id = list(PembuatEvent.objects.raw("SELECT * FROM pembuat_event ORDER BY id DESC"))[0].id
	id_id = int(latest_id[-2:]) + 1
	final_id = 'R00' + str(id_id)

	if request.method == 'POST':
		id = final_id
		nama_organisasi = request.POST['nama_organisasi']
		tingkatan = request.POST['tingkatan']
		email = request.POST['email']
		website = request.POST['website']
		contact_person = request.POST['contact_person']
		kategori = request.POST['kategori']
		deskripsi = request.POST['deskripsi']

		with connection.cursor() as c:
			sql = "INSERT INTO pembuat_event (id, nama, email, alamat_website, tingkatan, kategori, deskripsi, contact_person, logo) VALUES ('%s','%s','%s','%s','%s','%s','%s','%s',NULL)" % (id, nama_organisasi, email, website, tingkatan, kategori, deskripsi, contact_person)
			sql1 = "INSERT INTO organisasi (id_organisasi) VALUES ('%s')" % (id)
			c.execute(sql)
			c.execute(sql1)

		return HttpResponseRedirect(reverse('organisasi:index'))

	else:
		html = "add_organisasi.html"
		return render(request, html, response)

def form_update_organisasi(request, id_organisasi):
	response['id_current'] = id_organisasi

	if request.method == 'POST':
		id = id_organisasi
		nama_organisasi = request.POST['nama_organisasi']
		tingkatan = request.POST['tingkatan']
		email = request.POST['email']
		website = request.POST['website']
		contact_person = request.POST['contact_person']
		kategori = request.POST['kategori']
		deskripsi = request.POST['deskripsi']

		with connection.cursor() as c:
			sql = "UPDATE pembuat_event SET nama = '%s', tingkatan = '%s', email = '%s', website = '%s', contact_person = '%s', kategori = '%s', deskripsi = '%s' WHERE id = '%s'" % (nama_organisasi, email, website, tingkatan, kategori, deskripsi, contact_person, id)
			c.execute(sql)

		return HttpResponseRedirect(reverse('organisasi:index'))
	else:
		html = "update_organisasi.html"
		return render(request, html, response)

def delete_organisasi(request, id_organisasi):
	with connection.cursor() as c:
		c.execute("DELETE FROM organisasi WHERE id_organisasi=%s", [id_organisasi])
		return HttpResponseRedirect(reverse('organisasi:index'))

organisasi/templates/add_organisasi.html
{% extends "layout/base.html" %}

{% block content %}
  <div class="py-5 text-center text-white" style="background-image: linear-gradient(rgba(0, 0, 0, 0.75), rgba(0, 0, 0, 0.75)), url(https://static.pingendo.com/cover-bubble-dark.svg); background-position: center center, center center; background-size: cover, cover; background-repeat: repeat, repeat;">
    <div class="container">
      <div class="row" style="">
        <div class="mx-auto col-md-10 p-4">
          <h1 class="text-light"><b>Pendaftaran Organisasi Baru</b></h1>
          <p class="mb-4 lead text-light">Bantu kami memperkaya database kami dengan mendaftar. Pendaftaran gratis, tidak dipungut biaya.<br></p>

            <form action="{% url 'organisasi:add_organisasi' %}" method="POST">
            {% csrf_token %}
            <div class="form-row">
              <div class="form-group col-md-4"> <input type="text" class="form-control" name="nama_organisasi" id="nama_organisasi" placeholder="Nama Organisasi" required="required"> </div>
              <div class="form-group col-md-4"> <input type="email" class="form-control" name="email" id="email" placeholder="Email"> </div>
              <div class="form-group col-md-4"> <input type="text" class="form-control" id="contact_person" name="contact_person" placeholder="Contact Person"> </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-4">
                  <input type="text" class="form-control" id="website" name="website" placeholder="Website" required="required"> </div>
                  <div class="form-group col-md-4">
                    <div class="btn-group">
                      <select name="tingkatan" id="tingkatan" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <option selected="selected" disabled>Tingkatan Organisasi</option>
                          {% for x,y in tingkatan_dropdown.fields.tingkatan.choices %}
                              <option value="{{ x }}" class="dropdown-item">{{ x }}</option>
                          {% endfor %}
                      </select>
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                    </div>
                  </div>
              <div class="form-group col-md-4">
                  <div class="btn-group">
                      <select name="kategori" id="kategori" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <option selected="selected" disabled>Kategori Organisasi</option>
                          {% for x,y in kategori_dropdown.fields.kategori.choices %}
                              <option value="{{ x }}" class="dropdown-item">{{ x }}</option>
                          {% endfor %}
                      </select>
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                  </div>
              </div>
            </div>
            <div class="form-group"> <textarea class="form-control" id="deskripsi" name="deskripsi" rows="3" placeholder="Deskripsi Singkat Organisasi"></textarea> </div>
            <button type="submit" class="btn btn-secondary">Daftarkan!</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

organisasi/templates/list_organisasi.html
{% extends "layout/base.html" %}

{% block content %}
<div class="py-5" style="background-image: url(https://static.pingendo.com/cover-bubble-dark.svg); background-position: right bottom;  background-size: cover; background-repeat: repeat; background-attachment: fixed;">
    <div class="container">
      <div class="row">
        <div class="mx-auto col-md-8 text-center">
          <h1 contenteditable="true"><b>Daftar Organisasi</b></h1>
          <div class="row">
            <div class="col-md-12"><a class="btn btn-primary" href="{% url 'organisasi:add_organisasi' %}"><b><b>Tambahkan Organisasi baru...</b></b></a></div>
          </div>
        </div>
      </div>

      <div class="row">
        {% for organisasi in list_organisasi %}
            <div class="col-lg-3 col-6 p-3">
              <div class="card"> <img class="card-img-top" src="https://static.pingendo.com/img-placeholder-1.svg" alt="Card image cap">
                <div class="card-body">
                  <h5 class="card-title"> <b>{{ organisasi.nama }}</b> </h5>
                  <p class="card-text">{{ organisasi.kategori }} | {{ organisasi.tingkatan }}</p>
                  <p class="card-text">Email: {{ organisasi.email }}</p>
                  <a href="https://{{ organisasi.alamat_website }}"><p class="card-text">Website</p></a>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12 my-2"><a class="btn btn-primary" href="{% url 'organisasi:update_organisasi' organisasi.id %}"><b>&nbsp; Update Organisasi...&nbsp;</b></a></div>
              </div><a class="btn btn-danger" href="{% url 'organisasi:delete_organisasi' organisasi.id %}"><b>&nbsp; Delete Organisasi...&nbsp; &nbsp;</b></a>
            </div>
        {% endfor %}
      </div>
    </div>
</div>

{% endblock %}

organisasi/templates/update_organisasi.html
{% extends "layout/base.html" %}

{% block content %}
  <div class="py-5 text-center text-white" style="background-image: linear-gradient(rgba(0, 0, 0, 0.75), rgba(0, 0, 0, 0.75)), url(https://static.pingendo.com/cover-bubble-dark.svg); background-position: center center, center center; background-size: cover, cover; background-repeat: repeat, repeat;">
    <div class="container">
      <div class="row" style="">
        <div class="mx-auto col-md-10 p-4">
          <h1 class="text-light"><b>Pembaruan Informasi Organisasi</b></h1>
          <p class="mb-4 lead text-light">Bantu kami memperkaya database kami dengan memperbarui informasi terkait Organisasi.<br></p>

            <form action="{% url 'organisasi:update_organisasi' id_current %}" method="POST">
            {% csrf_token %}
            <div class="form-row">
              <div class="form-group col-md-4"> <input type="text" class="form-control" name="nama_organisasi" id="nama_organisasi" placeholder="Nama Organisasi" required="required"> </div>
              <div class="form-group col-md-4"> <input type="email" class="form-control" name="email" id="email" placeholder="Email"> </div>
              <div class="form-group col-md-4"> <input type="text" class="form-control" id="contact_person" name="contact_person" placeholder="Contact Person"> </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-4">
                  <input type="text" class="form-control" id="website" name="website" placeholder="Website" required="required"> </div>
                    <div class="form-group col-md-4">
                    <div class="btn-group">
                      <select name="tingkatan" id="tingkatan" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <option selected="selected" disabled>Tingkatan Organisasi</option>
                          {% for x,y in tingkatan_dropdown.fields.tingkatan.choices %}
                              <option value="{{ x }}" class="dropdown-item">{{ x }}</option>
                          {% endfor %}
                      </select>
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                    </div>
                  </div>
              <div class="form-group col-md-4">
                  <div class="btn-group">
                      <select name="kategori" id="kategori" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <option selected="selected" disabled>Kategori Organisasi</option>
                          {% for x,y in kategori_dropdown.fields.kategori.choices %}
                              <option value="{{ x }}" class="dropdown-item">{{ x }}</option>
                          {% endfor %}
                      </select>
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                  </div>
              </div>
            </div>
            <div class="form-group"> <textarea class="form-control" id="deskripsi" name="deskripsi" rows="3" placeholder="Deskripsi Singkat Organisasi"></textarea> </div>
            <button type="submit" class="btn btn-secondary">Daftarkan!</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}