event/urls.py
from django.urls import path
from .views import list_of_event, form_add_event, delete_event, form_update_event

urlpatterns = [
    path('', list_of_event, name='index'),
    path('add_event/', form_add_event, name='add_event'),
    path('update_event/<str:id_event>/', form_update_event, name='update_event'),
    path('delete_event/<str:id_event>/', delete_event, name='delete_event'),
]

main/urls.py
from django.urls import path
from .views import main_index, logout

urlpatterns = [
    path('', main_index, name='index'),
    path('logout/', logout, name='logout'),
]

simui/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('login.urls', 'login'), namespace="login")),
    path('main/', include(('main.urls', 'main'), namespace="main")),
    path('organisasi/', include(('organisasi.urls', 'organisasi'), namespace="organisasi")),
    path('kepanitiaan/', include(('kepanitiaan.urls', 'kepanitiaan'), namespace="kepanitiaan")),
    path('event/', include(('event.urls', 'event'), namespace="event")),
]

event/models.py
from django.db import models

# Create your models here.

event/forms.py
from django import forms
from simui_db.models import *

KATEGORI_CHOICES = []
ORGANISASI_CHOICES = []
KEPANITIAAN_CHOICES = []

kategori_data = list(KategoriEvent.objects.raw("SELECT DISTINCT nomor, nama FROM kategori_event"))
organisasi_data = list(PembuatEvent.objects.raw("SELECT DISTINCT id, nama FROM pembuat_event pe, organisasi o WHERE pe.id = o.id_organisasi"))
kepanitiaan_data = list(PembuatEvent.objects.raw("SELECT DISTINCT id, nama FROM pembuat_event pe, kepanitiaan k WHERE pe.id = k.id_kepanitiaan"))


for i in range(len(kategori_data)):
	if (kategori_data[i].nomor, kategori_data[i].nama) not in KATEGORI_CHOICES:
		KATEGORI_CHOICES.append((kategori_data[i].nomor, kategori_data[i].nama))

for i in range(len(organisasi_data)):
	if (organisasi_data[i].id, organisasi_data[i].nama) not in ORGANISASI_CHOICES:
		ORGANISASI_CHOICES.append((organisasi_data[i].id, organisasi_data[i].nama))

for i in range(len(kepanitiaan_data)):
	if (kepanitiaan_data[i].id, kepanitiaan_data[i].nama) not in KEPANITIAAN_CHOICES:
		KEPANITIAAN_CHOICES.append((kepanitiaan_data[i].id, kepanitiaan_data[i].nama))

class KepanitiaanChoice(forms.Form):
	kepanitiaan = forms.ChoiceField(
		choices=KEPANITIAAN_CHOICES,
		required=False,
		widget=forms.Select(
			attrs={
				'class': 'btn btn-primary dropdown-toggle dropdown-toggle-split',
				'data-toggle': 'dropdown',
				'aria-expanded': 'false',
				'type': 'button',
			}
		)
	)

class OrganisasiChoice(forms.Form):
	organisasi = forms.ChoiceField(
		choices=ORGANISASI_CHOICES,
		required=False,
		widget=forms.Select(
			attrs={
				'class': 'btn btn-primary dropdown-toggle dropdown-toggle-split',
				'data-toggle': 'dropdown',
				'aria-expanded': 'false',
				'type': 'button',
			}
		)
	)

class KategoriChoice(forms.Form):
	kategori = forms.ChoiceField(
		choices=KATEGORI_CHOICES,
		required=True,
		widget=forms.Select(
			attrs={
				'class':'form-control',
			}
		),
	)

event/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.db import connection
from simui_db.models import *
from .forms import KategoriChoice, OrganisasiChoice, KepanitiaanChoice

response = {
	'event_title': 'Event - Sistem Informasi Mahasiswa UI (SIMUI)',
	'author': 'Basis Data Ganjil 2018/19',
	'kategori_dropdown' : KategoriChoice(),
    'organisasi_dropdown': OrganisasiChoice(),
	'kepanitiaan_dropdown': KepanitiaanChoice(),
}

def list_of_event(request):
	list_event = list(Event.objects.raw("SELECT * FROM event e, pembuat_event pe WHERE pe.id = e.id_pembuat_event ORDER BY e.id_event DESC"))

	response['list_event'] = list_event

	html = "list_event.html"
	return render(request, html, response)

def form_add_event(request):
	latest_id = list(Event.objects.raw("SELECT * FROM event ORDER BY id_event DESC"))[0].id_event
	id_id = latest_id+1
	final_id = id_id

	if request.method == 'POST':
		id_pembuat_event = ''
		id = final_id
		id_organisasi = request.POST['organisasi']
		id_kepanitiaan = request.POST['kepanitiaan']
		nama_event = request.POST['nama_event']
		tanggal = request.POST['tanggal']
		waktu = request.POST['waktu']
		nomor_kategori = request.POST['kategori']
		deskripsi = request.POST['deskripsi']
		kapasitas = request.POST['kapasitas']
		sifat_event = request.POST['sifat_event']
		harga_tiket = request.POST['harga_tiket']
		lokasi = request.POST['lokasi']

		if id_organisasi != '':
			id_pembuat_event = id_organisasi
		if id_kepanitiaan != '':
			id_pembuat_event = id_kepanitiaan

		with connection.cursor() as c:
			sql = "INSERT INTO event (id_pembuat_event, id_event, nama, tanggal, waktu, nomor_kategori, deskripsi_singkat, kapasitas, sifat_event, harga_tiket, lokasi) VALUES ('%s',%s,'%s','%s','%s','%s','%s',%s,'%s',%s,'%s')" % (id_pembuat_event, id, nama_event, tanggal, waktu, nomor_kategori, deskripsi, kapasitas, sifat_event, harga_tiket, lokasi)
			c.execute(sql)

		return HttpResponseRedirect(reverse('event:index'))

	else:
		html = "add_event.html"
		return render(request, html, response)

def form_update_event(request, id_event):
	response['id_current'] = id_event
	if request.method == 'POST':
		id_pembuat_event = ''
		id = id_event
		id_organisasi = request.POST['organisasi']
		id_kepanitiaan = request.POST['kepanitiaan']
		nama_event = request.POST['nama_event']
		tanggal = request.POST['tanggal']
		waktu = request.POST['waktu']
		nomor_kategori = request.POST['kategori']
		deskripsi = request.POST['deskripsi']
		kapasitas = request.POST['kapasitas']
		sifat_event = request.POST['sifat_event']
		harga_tiket = request.POST['harga_tiket']
		lokasi = request.POST['lokasi']

		if id_organisasi != '':
			id_pembuat_event = id_organisasi
		if id_kepanitiaan != '':
			id_pembuat_event = id_kepanitiaan

		with connection.cursor() as c:
			sql = "UPDATE event SET id_pembuat_event = '%s', nama = '%s', tanggal = '%s', waktu = '%s', nomor_kategori = '%s', deskripsi_singkat = '%s', kapasitas = %s, sifat_event = '%s', harga_tiket = %s, lokasi = '%s' WHERE id_event = %s" % (id_pembuat_event, nama_event, tanggal, waktu, nomor_kategori, deskripsi, kapasitas, sifat_event, harga_tiket, lokasi, id)
			c.execute(sql)

		return HttpResponseRedirect(reverse('event:index'))
	else:
		html = "update_event.html"
		return render(request, html, response)

def delete_event(request, id_event):
	with connection.cursor() as c:
		c.execute("DELETE FROM event WHERE id_event= %s", [id_event])
		return HttpResponseRedirect(reverse('event:index'))

event/templates/add_event.html
{% extends "layout/base.html" %}

{% block content %}
  <div class="py-5 text-center text-white" style="background-image: linear-gradient(rgba(0, 0, 0, 0.75), rgba(0, 0, 0, 0.75)), url(https://static.pingendo.com/cover-bubble-dark.svg); background-position: center center, center center; background-size: cover, cover; background-repeat: repeat, repeat;">
    <div class="container">
      <div class="row" style="">
        <div class="mx-auto col-md-10 p-4">
          <h1 class="text-light"><b>Pendaftaran Event Baru</b></h1>
          <p class="mb-4 lead text-light">Bantu kami memperkaya database kami dengan mendaftar. Pendaftaran gratis, tidak dipungut biaya.<br></p>

            <form action="{% url 'event:add_event' %}" method="POST">
            {% csrf_token %}
            <div class="form-row">
              <div class="form-group col-md-4"> <input type="text" class="form-control" name="nama_event" id="nama_event" placeholder="Nama event" required="required"> </div>
              <div class="form-group col-md-4"> <input type="time" class="form-control" name="waktu" id="waktu" placeholder="Waktu Event"> </div>
              <div class="form-group col-md-4"> <input type="date" class="form-control" id="tanggal" name="tanggal" placeholder="Tanggal Event"> </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-4">
                  <input type="text" class="form-control" id="sifat_event" name="sifat_event" placeholder="Sifat Event" required="required"> </div>
                  <div class="form-group col-md-4">
                    <div class="btn-group">
                      <select name="organisasi" id="organisasi" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <option selected="selected" disabled>Organisasi</option>
                          {% for x,y in organisasi_dropdown.fields.organisasi.choices %}
                              <option value="{{ x }}" class="dropdown-item">{{ y }}</option>
                          {% endfor %}
                      </select>
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                    </div>
                  </div>
              <div class="form-group col-md-4">
                    <div class="btn-group">
                      <select name="kepanitiaan" id="kepanitiaan" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <option selected="selected" disabled>Kepanitiaan</option>
                          {% for x,y in kepanitiaan_dropdown.fields.kepanitiaan.choices %}
                              <option value="{{ x }}" class="dropdown-item">{{ y }}</option>
                          {% endfor %}
                      </select>
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                    </div>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-4"> <input type="number" class="form-control" name="harga_tiket" id="harga_tiket" placeholder="Harga Tiket" required="required"> </div>
              <div class="form-group col-md-4"> <input type="text" class="form-control" name="lokasi" id="waktu" placeholder="Lokasi Event"> </div>
              <div class="form-group col-md-4"> <input type="number" class="form-control" id="kapasitas" name="kapasitas" placeholder="Kapasitas Tempat"> </div>
            </div>
            <div class="form-group"> <textarea class="form-control" id="deskripsi" name="deskripsi" rows="3" placeholder="Deskripsi Singkat Event"></textarea> </div>
            <div class="form-group col-md-4">
                    <div class="btn-group">
                      <select name="kategori" id="kategori" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <option selected="selected" disabled>Kategori Event</option>
                          {% for x,y in kategori_dropdown.fields.kategori.choices %}
                              <option value="{{ x }}" class="dropdown-item">{{ y }}</option>
                          {% endfor %}
                      </select>
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                    </div>
                  </div>
            <button type="submit" class="btn btn-secondary">Daftarkan!</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

event/templates/list_event.html
{% extends "layout/base.html" %}

{% block content %}
<div class="py-5" style="background-image: url(https://static.pingendo.com/cover-bubble-dark.svg); background-position: right bottom;  background-size: cover; background-repeat: repeat; background-attachment: fixed;">
    <div class="container">
      <div class="row">
        <div class="mx-auto col-md-8 text-center">
          <h1 contenteditable="true"><b>Daftar Event</b></h1>
          <div class="row">
            <div class="col-md-12"><a class="btn btn-primary" href="{% url 'event:add_event' %}"><b><b>Tambahkan event baru...</b></b></a></div>
          </div>
        </div>
      </div>

      <div class="row">
        {% for event in list_event %}
            <div class="col-lg-3 col-6 p-3">
              <div class="card"> <img class="card-img-top" src="https://static.pingendo.com/img-placeholder-1.svg" alt="Card image cap">
                <div class="card-body">
                  <h5 class="card-title"> <b>{{ event.nama }}</b> </h5>
                  <p class="card-text">{{ event.kategori }} | {{ event.tingkatan }}</p>
                  <p class="card-text">Email: {{ event.email }}</p>
                  <a href="https://{{ event.alamat_website }}"><p class="card-text">Website</p></a>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12 my-2"><a class="btn btn-primary" href="{% url 'event:update_event' event.id_event %}"><b>  &nbsp; Update event...&nbsp;  </b></a></div>
              </div><a class="btn btn-danger" href="{% url 'event:delete_event' event.id_event %}"><b>  &nbsp; Delete event...&nbsp; &nbsp; </b></a>
            </div>
        {% endfor %}
      </div>
    </div>
</div>

{% endblock %}

event/templates/update_event.html
{% extends "layout/base.html" %}

{% block content %}
  <div class="py-5 text-center text-white" style="background-image: linear-gradient(rgba(0, 0, 0, 0.75), rgba(0, 0, 0, 0.75)), url(https://static.pingendo.com/cover-bubble-dark.svg); background-position: center center, center center; background-size: cover, cover; background-repeat: repeat, repeat;">
    <div class="container">
      <div class="row" style="">
        <div class="mx-auto col-md-10 p-4">
          <h1 class="text-light"><b>Pembaruan Informasi Event</b></h1>
          <p class="mb-4 lead text-light">Bantu kami memperkaya database kami dengan memperbarui event.<br></p>

            <form action="{% url 'event:update_event' id_current %}" method="POST">
            {% csrf_token %}
            <div class="form-row">
              <div class="form-group col-md-4"> <input type="text" class="form-control" name="nama_event" id="nama_event" placeholder="Nama event" required="required"> </div>
              <div class="form-group col-md-4"> <input type="time" class="form-control" name="waktu" id="waktu" placeholder="Waktu Event"> </div>
              <div class="form-group col-md-4"> <input type="date" class="form-control" id="tanggal" name="tanggal" placeholder="Tanggal Event"> </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-4">
                  <input type="text" class="form-control" id="sifat_event" name="sifat_event" placeholder="Sifat Event" required="required"> </div>
                  <div class="form-group col-md-4">
                    <div class="btn-group">
                      <select name="organisasi" id="organisasi" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <option selected="selected" disabled>Organisasi</option>
                          {% for x,y in organisasi_dropdown.fields.organisasi.choices %}
                              <option value="{{ x }}" class="dropdown-item">{{ y }}</option>
                          {% endfor %}
                      </select>
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                    </div>
                  </div>
              <div class="form-group col-md-4">
                    <div class="btn-group">
                      <select name="kepanitiaan" id="kepanitiaan" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <option selected="selected" disabled>Kepanitiaan</option>
                          {% for x,y in kepanitiaan_dropdown.fields.kepanitiaan.choices %}
                              <option value="{{ x }}" class="dropdown-item">{{ y }}</option>
                          {% endfor %}
                      </select>
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                    </div>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-4"> <input type="number" class="form-control" name="harga_tiket" id="harga_tiket" placeholder="Harga Tiket" required="required"> </div>
              <div class="form-group col-md-4"> <input type="text" class="form-control" name="lokasi" id="waktu" placeholder="Lokasi Event"> </div>
              <div class="form-group col-md-4"> <input type="number" class="form-control" id="kapasitas" name="kapasitas" placeholder="Kapasitas Tempat"> </div>
            </div>
            <div class="form-group"> <textarea class="form-control" id="deskripsi" name="deskripsi" rows="3" placeholder="Deskripsi Singkat Event"></textarea> </div>
            <div class="form-group col-md-4">
                    <div class="btn-group">
                      <select name="kategori" id="kategori" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <option selected="selected" disabled>Kategori Event</option>
                          {% for x,y in kategori_dropdown.fields.kategori.choices %}
                              <option value="{{ x }}" class="dropdown-item">{{ y }}</option>
                          {% endfor %}
                      </select>
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                    </div>
                  </div>
            <button type="submit" class="btn btn-secondary">Daftarkan!</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}