main/urls.py
from django.urls import path
from .views import main_index, logout

urlpatterns = [
    path('', main_index, name='index'),
    path('logout/', logout, name='logout'),
]

simui/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('login.urls', 'login'), namespace="login")),
    path('main/', include(('main.urls', 'main'), namespace="main")),
    path('organisasi/', include(('organisasi.urls', 'organisasi'), namespace="organisasi")),
    path('kepanitiaan/', include(('kepanitiaan.urls', 'kepanitiaan'), namespace="kepanitiaan")),
    path('event/', include(('event.urls', 'event'), namespace="event")),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from simui_db.models import *

response = {
    'main_title': 'Sistem Informasi Mahasiswa UI (SIMUI)',
    'author': 'Basis Data Ganjil 2018/19',
}

def main_index(request):
    if 'username' in request.session.keys():
        print("main page is executed!")

        loggedInUserName = request.session['username']
        listOrganisasi = list(Organisasi.objects.raw("SELECT * FROM pembuat_event pe, organisasi o WHERE pe.id = o.id_organisasi ORDER BY pe.id DESC LIMIT 5"))
        listKepanitiaan = list(Kepanitiaan.objects.raw("SELECT * FROM pembuat_event pe, kepanitiaan k WHERE pe.id = k.id_kepanitiaan ORDER BY pe.id DESC LIMIT 5"))
        listEvent = list(Event.objects.raw("SELECT * FROM event e ORDER BY e.id_event DESC LIMIT 5"))

        isAdminList = list(Admin.objects.raw("SELECT * FROM admin WHERE username = %s", [loggedInUserName]))
        isNonAdminList = list(NonAdmin.objects.raw("SELECT * FROM non_admin WHERE username = %s", [loggedInUserName]))
        isMahasiswaList = list(Mahasiswa.objects.raw("SELECT * FROM mahasiswa WHERE username = %s", [loggedInUserName]))
        isDosenList = list(Dosen.objects.raw("SELECT * FROM dosen WHERE username = %s", [loggedInUserName]))
        isStaffList = list(Staff.objects.raw("SELECT * FROM staff WHERE username = %s", [loggedInUserName]))
        isGuestList = list(Guest.objects.raw("SELECT * FROM guest WHERE username = %s", [loggedInUserName]))

        isNonAdmin = False
        isAdmin = False
        isDosen = False
        isMahasiswa = False
        isStaff = False
        isGuest = False

        if len(isNonAdminList) != 0:
            isNonAdmin = True
        if len(isAdminList) != 0:
            isAdmin = True
        if len(isDosenList) != 0:
            isDosen = True
        if len(isMahasiswaList) != 0:
            isMahasiswa = True
        if len(isStaffList) != 0:
            isStaff = True
        if len(isGuestList) != 0:
            isGuest = True

        print(isAdmin)

        if isAdmin == True:
            response['is_admin'] = True
            response['role'] = 'Admin'
            response['full_name'] = 'Admin_'+loggedInUserName

        else:
            response['is_admin'] = False
            response['full_name'] = list(NonAdmin.objects.raw("SELECT * FROM non_admin WHERE username = %s", [loggedInUserName]))[0].nama
            response['email'] = list(NonAdmin.objects.raw("SELECT * FROM non_admin WHERE username = %s", [loggedInUserName]))[0].email
            response['no_telepon'] = list(NonAdmin.objects.raw("SELECT * FROM non_admin WHERE username = %s", [loggedInUserName]))[0].no_telepon
            response['role'] = 'Non Admin'

            if isMahasiswa == True:
                response['is_mahasiswa'] = True
                response['npm'] = list(Mahasiswa.objects.raw("SELECT * FROM mahasiswa WHERE username = %s", [loggedInUserName]))[0].npm
                response['role'] = 'Mahasiswa'

            if isDosen == True:
                response['is_dosen'] = True
                response['nidn'] = list(Dosen.objects.raw("SELECT * FROM dosen WHERE username = %s", [loggedInUserName]))[0].nidn
                print("hehehe")
                response['role'] = 'Dosen'

            if isStaff == True:
                response['is_staff'] = True
                response['nip'] = list(Staff.objects.raw("SELECT * FROM staff WHERE username = %s", [loggedInUserName]))[0].nip
                response['role'] = 'Staff'

            if isGuest == True:
                response['is_guest'] = True
                response['pekerjaan'] = list(Guest.objects.raw("SELECT * FROM guest WHERE username = %s", [loggedInUserName]))[0].pekerjaan
                response['alamat'] = list(Guest.objects.raw("SELECT * FROM guest WHERE username = %s", [loggedInUserName]))[0].alamat
                response['role'] = 'Guest'

        response['list_organisasi'] = listOrganisasi
        response['list_kepanitiaan'] = listKepanitiaan
        response['list_event'] = listEvent
        response['logged_in_user_name'] = loggedInUserName
        html = "main.html"

        return render(request, html, response)

    else:
        print("#Not logged in")
        return HttpResponseRedirect(reverse("login:index"))


def logout(request):
    request.session.flush()
    return HttpResponseRedirect(reverse('login:index'))

main/templates/main.html
{% extends "layout/base.html" %}

{% block content %}
<div class="py-5 text-center">
<div class="container">
  <div class="row">
    <div class="mx-auto col-md-12">
      <h1 class="mb-3">Selamat Datang!</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12 col-6 p-4"> <img class="img-fluid d-block mb-3 mx-auto rounded-circle" src="https://static.pingendo.com/img-placeholder-2.svg" width="100" alt="Card image cap">
      <h4> <b>{{ full_name }}</b></h4>
      {% if is_admin %}
        <p style="	text-shadow: 0px 0px 4px black;"><b style="	text-shadow: 0px 0px 0px black;">{{ role }}</b></p>
      {% endif %}
      {% if is_mahasiswa %}
        <p style="	text-shadow: 0px 0px 4px black;"><b style="	text-shadow: 0px 0px 0px black;">{{ role }} - {{ npm }}</b></p>
        <p style="	text-shadow: 0px 0px 4px black;"><b style="	text-shadow: 0px 0px 0px black;">{{ email }} | {{ no_telepon }}</b></p>
      {% endif %}
      {% if is_dosen %}
        <p style="	text-shadow: 0px 0px 4px black;"><b style="	text-shadow: 0px 0px 0px black;">{{ role }} - {{ nidn }}</b></p>
        <p style="	text-shadow: 0px 0px 4px black;"><b style="	text-shadow: 0px 0px 0px black;">{{ email }} | {{ no_telepon }}</b></p>
      {% endif %}
      {% if is_staff %}
        <p style="	text-shadow: 0px 0px 4px black;"><b style="	text-shadow: 0px 0px 0px black;">{{ role }} - {{ nip }}</b></p>
        <p style="	text-shadow: 0px 0px 4px black;"><b style="	text-shadow: 0px 0px 0px black;">{{ email }} | {{ no_telepon }}</b></p>
      {% endif %}
      {% if is_guest %}
        <p style="	text-shadow: 0px 0px 4px black;"><b style="	text-shadow: 0px 0px 0px black;">{{ role }} - {{ pekerjaan }}</b></p>
        <p style="	text-shadow: 0px 0px 4px black;"><b style="	text-shadow: 0px 0px 0px black;">{{ alamat }}</b></p>
        <p style="	text-shadow: 0px 0px 4px black;"><b style="	text-shadow: 0px 0px 0px black;">{{ email }} | {{ no_telepon }}</b></p>
      {% endif %}
    </div>
  </div>
</div>
</div>
<div class="py-5 text-center text-white" style="background-image: linear-gradient(rgba(0, 0, 0, 0.75), rgba(0, 0, 0, 0.75)), url(https://static.pingendo.com/cover-bubble-dark.svg); background-position: center center, center center; background-size: cover, cover; background-repeat: repeat, repeat;">
<div class="container">
  <div class="row">
    <div class="mx-auto col-md-12">
      <h1 class="mb-3">List Kepanitiaan, Organisasi, dan Event</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4 col-md-6 p-4">
      <h4> <b>Kepanitiaan</b></h4>
      <div class="row">
        <div class="col-md-12">
          <div class="list-group">
            {% for kepanitiaan in list_kepanitiaan %}
            <a href="#" class="list-group-item list-group-item-action">{{ kepanitiaan.nama }}</a>
            {% endfor %}
          </div>
        </div>
      </div>
        <br>
      <div class="row">
        <div class="col-md-12"><a class="btn btn-primary" href="{% url 'kepanitiaan:index' %}"><b>Lihat Semua Kepanitiaan...</b></a></div>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 p-4">
      <h4> <b>Organisasi</b></h4>
      <div class="col-md-12">
        <div class="list-group">
            {% for organisasi in list_organisasi %}
                <a href="#" class="list-group-item list-group-item-action">{{ organisasi.nama }}</a>
            {% endfor %}
        </div>
      </div>
        <br>
      <div class="row">
        <div class="col-md-12"><a class="btn btn-primary" href="{% url 'organisasi:index' %}"><b>Lihat Semua Organisasi...</b></a></div>
      </div>
    </div>
    <div class="col-lg-4 p-4">
      <h4>Event</h4>
      <div class="row">
        <div class="col-md-12">
          <div class="list-group">
            {% for event in list_event %}
            <a href="#" class="list-group-item list-group-item-action">{{ event.nama }}</a>
            {% endfor %}
          </div>
        </div>
      </div>
        <br>
      <div class="row">
        <div class="col-md-12"><a class="btn btn-primary" href="{% url 'event:index' %}"><b>Lihat Semua Event...</b></a></div>
      </div>
    </div>
  </div>
</div>
</div>

{% endblock %}